function [afe, winInfo] = setAudioFeatureExtractor(winInfo)

winInfo = extrctWinInfo(winInfo);

afe = audioFeatureExtractor(...
    'SampleRate',       winInfo.fs, ...
    'Window',           winInfo.win, ...
    'OverlapLength',    winInfo.numSamplesOverlapBetweenWin, ...
    'melSpectrum',      true ...
    );

setExtractorParams( ...
    afe,                        'melSpectrum', ...
    'SpectrumType',             winInfo.SpectrumType, ... % 'power' (default) | 'magnitude'
    'NumBands',                 winInfo.numBands, ...
    "WindowNormalization",      winInfo.WindowNormalization, ... % true (default) | false
    'FilterBankNormalization',  winInfo.FilterBankNormalization ... % 'bandwidth' (default) | 'area' | 'none'
    );

end

