%%

% remove previous data
close all; clc; clear;

% load metadata from database
prevFolder = cd('..\..\..\..\');
folderPath = pwd;
folderName = folderPath + "DataBase\coughvid\coughvid-dataset-03-02-21";
metaDataOrigin = readtable(folderName + "\metadata_compiled.csv"); % metadata
metaDataOrigin = metaDataOrigin(:, [1 3 7 8 11 12 20 22 30 32 40 42 50]);
cd(prevFolder);

% see all possible options for each category
optStatus = unique(metaDataOrigin.status); % covid status
optQuality = unique(metaDataOrigin.quality_1); % cough quality
optDiagnosis = unique(metaDataOrigin.diagnosis_1); % covid diagnosis

% save options as strings
status = string(metaDataOrigin.status);
age = metaDataOrigin.age;
quality_1 = string(metaDataOrigin.quality_1);
quality_2 = string(metaDataOrigin.quality_2);
quality_3 = string(metaDataOrigin.quality_3);
quality_4 = string(metaDataOrigin.quality_4);
diagnosis_1 = string(metaDataOrigin.diagnosis_1);
diagnosis_2 = string(metaDataOrigin.diagnosis_2);
diagnosis_3 = string(metaDataOrigin.diagnosis_3);
diagnosis_4 = string(metaDataOrigin.diagnosis_4);

% remove bad subjects
indxStatus = status == "COVID-19" | status == "healthy";
indxAgeBad = isnan(age) | age < 10 | age > 90;
indxDiagnosis = ...
    diagnosis_1 == "healthy_cough" | diagnosis_1 == "lower_infection" | ...
    diagnosis_1 == "obstructive_disease" | diagnosis_1 == "upper_infection" | ...
    diagnosis_1 == "COVID-19" | ...
    diagnosis_2 == "healthy_cough" | diagnosis_2 == "lower_infection" | ...
    diagnosis_2 == "obstructive_disease" | diagnosis_2 == "upper_infection" | ...
    diagnosis_2 == "COVID-19" | ...
    diagnosis_3 == "healthy_cough" | diagnosis_3 == "lower_infection" | ...
    diagnosis_3 == "obstructive_disease" | diagnosis_3 == "upper_infection" | ...
    diagnosis_3 == "COVID-19" | ...
    diagnosis_4 == "healthy_cough" | diagnosis_4 == "lower_infection" | ...
    diagnosis_4 == "obstructive_disease" | diagnosis_4 == "upper_infection" | ...
    diagnosis_4 == "COVID-19";
indxQualityGood = ...
    quality_1 == "good" | quality_1 == "ok" | ...
    quality_2 == "good" | quality_2 == "ok" | ...
    quality_3 == "good" | quality_3 == "ok" | ...
    quality_4 == "good" | quality_4 == "ok";
indxQualityBad = ...
    quality_1 == "no_cough" | quality_1 == "poor" | ...
    quality_2 == "no_cough" | quality_2 == "poor" | ...
    quality_3 == "no_cough" | quality_3 == "poor" | ...
    quality_4 == "no_cough" | quality_4 == "poor";

% update metaData
metaData = metaDataOrigin((indxStatus .* (1-indxAgeBad)) > 0, :);
metaData = metaDataOrigin((indxStatus .* (1-indxAgeBad) .* indxDiagnosis) > 0, :);
metaData = metaDataOrigin((indxStatus .* (1-indxAgeBad) .* indxDiagnosis ...
    .* indxQualityGood .* (1-indxQualityBad)) > 0, :);

numPos = sum(metaData.status == "COVID-19");
numNeg = sum(metaData.status == "healthy");

% find positive indices based on strings
indxStatusPos = status == "COVID-19";
indxStatusNeg = status == "healthy";
indxAgeBad = isnan(age) | age < 10 | age > 90;
indxQualityGood = ...
    quality_1 == "good" | quality_1 == "ok" | ...
    quality_2 == "good" | quality_2 == "ok" | ...
    quality_3 == "good" | quality_3 == "ok" | ...
    quality_4 == "good" | quality_4 == "ok";
indxQualityBad = ...
    quality_1 == "no_cough" | quality_1 == "poor" | ...
    quality_2 == "no_cough" | quality_2 == "poor" | ...
    quality_3 == "no_cough" | quality_3 == "poor" | ...
    quality_4 == "no_cough" | quality_4 == "poor";
indxDiagnosisPos = ...
    diagnosis_1 == "COVID-19" | ...
    diagnosis_2 == "COVID-19" | ...
    diagnosis_3 == "COVID-19" | ...
    diagnosis_4 == "COVID-19";
indxDiagnosisNeg = ...
    diagnosis_1 == "healthy_cough" | diagnosis_1 == "lower_infection" | ...
    diagnosis_1 == "obstructive_disease" | diagnosis_1 == "upper_infection" | ...
    diagnosis_2 == "healthy_cough" | diagnosis_2 == "lower_infection" | ...
    diagnosis_2 == "obstructive_disease" | diagnosis_2 == "upper_infection" | ...
    diagnosis_3 == "healthy_cough" | diagnosis_3 == "lower_infection" | ...
    diagnosis_3 == "obstructive_disease" | diagnosis_3 == "upper_infection" | ...
    diagnosis_4 == "healthy_cough" | diagnosis_4 == "lower_infection" | ...
    diagnosis_4 == "obstructive_disease" | diagnosis_4 == "upper_infection";
% indxDiagnosisNeg = ...
%     diagnosis_1 == "healthy_cough" | ...
%     diagnosis_2 == "healthy_cough" | ...
%     diagnosis_3 == "healthy_cough" | ...
%     diagnosis_4 == "healthy_cough";

% combine all options
indxPos = ...
    (indxStatusPos .* (1-indxAgeBad) .* indxQualityGood .* (1-indxQualityBad) .* ...
    indxDiagnosisPos .* (1-indxDiagnosisNeg)) > 0;
indxNeg = ...
    (indxStatusNeg .* (1-indxAgeBad) .* indxQualityGood .* (1-indxQualityBad) .* ...
    indxDiagnosisNeg .* (1-indxDiagnosisPos)) > 0;

% update metaData
metaDataPos = metaDataOrigin(indxPos, :);
metaDataPos.class = repmat("positive", height(metaDataPos), 1);
metaDataNeg = metaDataOrigin(indxNeg, :);
metaDataNeg.class = repmat("negative", height(metaDataNeg), 1);
metaData = [metaDataNeg ; metaDataPos];
