function metadata = loadMetadata

% load metadata from excel files
metadataVocaPos = readtable('metadata_voca_positive.xlsx');
metadataVocaNeg = readtable('metadata_voca_negative.xlsx');

metadataCoughvid = readtable('metaDataCoughvid.xlsx');
metadataCoughvidPos = metadataCoughvid(metadataCoughvid.class == "positive", :);
metadataCoughvidNeg = metadataCoughvid(metadataCoughvid.class == "negative", :);

metadataCoswara = readtable('metadata coswara final.csv');
metadataCoswaraPos = metadataCoswara(metadataCoswara.class == "positive", :);
metadataCoswaraNeg = metadataCoswara(metadataCoswara.class == "negative", :);

% files locations
audioFileLocation = string([ ...
    metadataVocaPos.audio_file_location ; ...
    metadataVocaNeg.audio_file_location ; ...
    metadataCoughvidPos.audioFileLocation ; ...
    metadataCoughvidNeg.audioFileLocation ; ...
    metadataCoswaraPos.folder ; ...
    metadataCoswaraNeg.folder ...
    ]);

% dataset
ds = string([ ...
    metadataVocaPos.ds ; ...
    metadataVocaNeg.ds ; ...
    metadataCoughvidPos.dataset ; ...
    metadataCoughvidNeg.dataset ; ...
    metadataCoswaraPos.dataset ; ...
    metadataCoswaraNeg.dataset ...
    ]);

% class
class = string([ ...
    metadataVocaPos.class ; ...
    metadataVocaNeg.class ; ...
    metadataCoughvidPos.class ; ...
    metadataCoughvidNeg.class ; ...
    metadataCoswaraPos.class ; ...
    metadataCoswaraNeg.class ...
    ]);

% age
age = [ ...
    metadataVocaPos.age ; ...
    metadataVocaNeg.age ; ...
    metadataCoughvidPos.age ; ...
    metadataCoughvidNeg.age ; ...
    metadataCoswaraPos.a ; ...
    metadataCoswaraNeg.a ...
    ];

% gender
gender = string([ ...
    metadataVocaPos.gender ; ...
    metadataVocaNeg.gender ; ...
    metadataCoughvidPos.gender ; ...
    metadataCoughvidNeg.gender ; ...
    metadataCoswaraPos.g ; ...
    metadataCoswaraNeg.g ...
    ]);

% save metadata in table and excel file
metadata = table( ...
    audioFileLocation, ds, class, age, gender, ...
    'VariableNames', {'audioFileLocation', 'dataset', 'class', 'age', 'gender'});
writetable(metadata, 'metadata.xlsx', 'WriteMode', 'replacefile');

end

